---
swagger: "2.0"
info:
  description: "Server Provisoning API "
  version: "1.0.0"
  title: "Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "provisioning.company.com"
basePath: "/api"
tags:
- name: "provisioning"
  description: "provisioning endpoints"
- name: "discovery"
  description: "discovery endpoints"
schemes:
- "http"
paths:
  /provisioning/port:
    get:
      tags:
      - "provisioning"
      summary: "retrieve server connectivity requests"
      description: "Retrieve a list of ports requesting configuration changes"
      operationId: "get_requests"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid request"
      x-swagger-router-controller: "swagger_server.controllers.provisioning_controller"
    post:
      tags:
      - "provisioning"
      summary: "Add a provisioning request"
      description: "This endpoint is used to submit a new provisioing request"
      operationId: "add_provisioning_request"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Provision request object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/PortProvisionRequest"
      responses:
        200:
          description: "success"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.provisioning_controller"
  /provisioning/port/{requestId}:
    get:
      tags:
      - "provisioning"
      summary: "get provisioning request by ID"
      description: "Returns a single provisioning request"
      operationId: "get_provisioning_request_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "requestId"
        in: "path"
        description: "ID of request to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "not found"
      x-swagger-router-controller: "swagger_server.controllers.provisioning_controller"
    delete:
      tags:
      - "provisioning"
      summary: "Deletes a port provisioning request"
      description: ""
      operationId: "delete_provisioning_request"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "requestId"
        in: "path"
        description: "provisioning request id to delete"
        required: true
        type: "string"
      responses:
        200:
          description: "success"
        400:
          description: "Invalid ID supplied"
        404:
          description: "not found"
      x-swagger-router-controller: "swagger_server.controllers.provisioning_controller"
  /discovery/link:
    get:
      tags:
      - "discovery"
      summary: "List discovery objects"
      description: "Retrieve a list of ports requesting configuration changes"
      operationId: "get_all_discoveries"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties: {}
        400:
          description: "Invalid request"
      x-swagger-router-controller: "swagger_server.controllers.discovery_controller"
    post:
      tags:
      - "discovery"
      summary: "Add a discovery object"
      description: "This endpoint is used to submit a new provisioing request"
      operationId: "add_discovery"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "discovery object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/DiscoveryObject"
      responses:
        200:
          description: "success"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.discovery_controller"
  /discovery/link/{discoveryId}:
    get:
      tags:
      - "discovery"
      summary: "get a discovery object by ID"
      description: "Returns a single discovery request"
      operationId: "get_discovery_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "discoveryId"
        in: "path"
        description: "ID of request to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PortProvisionRequest"
        400:
          description: "Invalid ID supplied"
        404:
          description: "not found"
      x-swagger-router-controller: "swagger_server.controllers.discovery_controller"
    delete:
      tags:
      - "discovery"
      summary: "Deletes a discovery object"
      description: ""
      operationId: "delete_discovery_by_id"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "discoveryId"
        in: "path"
        description: "discovery id to delete"
        required: true
        type: "string"
      responses:
        200:
          description: "success"
        400:
          description: "Invalid ID supplied"
        404:
          description: "not found"
      x-swagger-router-controller: "swagger_server.controllers.discovery_controller"
definitions:
  PortProvisionRequest:
    type: "object"
    required:
    - "interface"
    - "requestor"
    - "switch"
    - "vlans"
    properties:
      id:
        type: "string"
        readOnly: true
      interface:
        type: "string"
        example: "Ethernet1/1"
      requestor:
        type: "string"
        example: "jsmith@company.com"
      switch:
        type: "string"
        example: "10.1.1.1"
        description: "ip/hostname of switch"
      vlans:
        type: "array"
        example:
        - 1
        - 2
        - 3
        - 4
        items:
          type: "integer"
  DiscoveryObject:
    type: "object"
    required:
    - "interface"
    - "mac_addresses"
    - "switch"
    properties:
      id:
        type: "string"
        readOnly: true
      interface:
        type: "string"
        example: "Ethernet1/1"
      switch:
        type: "string"
        example: "10.1.1.1"
        description: "ip/hostname of switch"
      mac_addresses:
        type: "array"
        example:
        - "0000.0000.0000"
        - "1111.1111.1111"
        items:
          type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
